# TODO Start: [Student] URL
image: registry.spring25b.secoder.net/tool/deployer
# TODO End

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - main

# TODO Start: [Student] Complete test stage
.test-template:
  image: node:22
  before_script:
    - corepack enable
    - pnpm config set registry https://npm-cache-sepi.app.spring25a.secoder.net/
    - pnpm install --frozen-lockfile

unit-test:
  extends: .test-template
  stage: test
  script:
    - pnpm test
  after_script:
    - sonar-scanner

style-test:
  extends: .test-template
  stage: test
  script:
    - pnpm lint
# TODO End

deploy:
  stage: deploy
  script:
    - export DEPLOY_ENV=$GITLAB_USER_LOGIN
    # TODO Start: [Student] URL
    - export API_SERVER=https://deployer.spring25b.secoder.net/api
    # TODO End
    - deployer dyno replace frontend $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  only:
    - main
