# TODO Start: [Student] URL
image: registry.spring25b.secoder.net/tool/deployer
# TODO End

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - dev

# TODO Start: [Student] Complete test stage
.test:
  image: node:22
  stage: test

  before_script:
    - corepack enable
    - pnpm config set registry https://npm-cache-sepi.app.spring25a.secoder.net/
    - pnpm install

# unit-test:
#   extends: .test

#   script:
#     - pnpm test
#   after_script:
#     - SUFFIX=$RANDOM
#     - curl "http://api.spring25b.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
#     - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
#     - sed -i 's/sonarqube.secoder.net/sonarqube.spring25b.secoder.net/g' /opt/sonar-scanner/conf/sonar-scanner.properties
#     - sed -i 's/api.secoder.net/api.spring25b.secoder.net/g' /opt/sonar-scanner/bin/sonar-scanner
#     - /opt/sonar-scanner/bin/sonar-scanner

style-test:
  extends: .test
  allow_failure: true

  script:
    - pnpm lint
# TODO End

deploy:
  stage: deploy
  script:
    - export API_SERVER=https://deployer.spring25b.secoder.net/api
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - dev